name: kernel-snap-example
version: 0
summary: a snappy DIY kernel build using snapcraft
description: kernel as a snap
icon: icon.png
type: kernel

parts:
  kernel:
    plugin: kernel
    #source: ../../target/kernel
    source: https://github.com/torvalds/linux
    source-type: git
    kdefconfig: x86_64_defconfig
    kconfigs:
      - CONFIG_LOCALVERSION="-kernel-snap-example"
      - CONFIG_LOCALVERSION_AUTO=y
      - CONFIG_SQUASHFS=y
      - CONFIG_SQUASHFS_XZ=y
    kernel-initrd-mods:
      - nf_nat
    kernel-initrd-fws:
      - lib/firmware/atmsar11.fw
    kernel-image-path: arch/x86/boot/bzImage
